### ISSUE TITLE
RememberMe.loginWithPassword argument types

### ISSUE THREAD

**Issue by evg1n** [tprzytula/Meteor-Remember-Me#38]
Hello,

I think it would be a better practice to change argument type "username" from `String` to String or Object, because it is as such in `Meteor.loginWithPassword( username || email [Type: String or Object], password, callback)`.

Because, some websites do not have username implementation and logs in only with email. So when you use `(email, password) => Meteor.loginWithPassword({email: email}, password, [callback])` it works.

IMHO you should also implement this argument type to your RememberMe class.

Nice add-on, keep up the good work!

**Comment by tprzytula** [comment]
I've updated the code & docs with the fixes. They are now following the same wording as the official Meteor documentation & code does.
