### ISSUE TITLE
Broken code binding in latest meteor

### ISSUE THREAD

**Issue by justinr1234** [tprzytula/Meteor-Remember-Me#6]
`this` doesn't automatically bind if you upgrade to the latest Meteor version:

https://github.com/tprzytula/Meteor-Remember-Me/blob/master/client/index.js#L34

Should likely rewrite these as arrow functions:

`getLoginWithPasswordMethod = () => {`

Further down the code fails here: https://github.com/tprzytula/Meteor-Remember-Me/blob/master/client/index.js#L64

Complaining that `this.getLoginWithPasswordMethod` is non-existent.

**Comment by tprzytula** [comment]
Thank you for reporting the issue.

I've tried to reproduced it but I could not with the Meteor 1.7-rc.5 release + Blaze.
Here is my reproduction repo: https://github.com/tprzytula/Meteor-RememberMe-Issue-Reproduction

Do you use React? I think the context might be different if you invoke the method directly from the `render()`.

This evening I will try to add React to the reproduction repo and try to simulate this issue and apply the fix.

**Comment by tprzytula** [comment]
I managed to reproduce the issue and applied the fix by changing the method to arrow functions as you suggested.

Thank you!

You can check the version 0.2.1. Let me know if you will encounter any additional issues.

**Comment by justinr1234** [comment]
I’ll check as soon as I can, thanks!
